version: '3'

services:
  nginx:
    build: ./nginx/
    ports:
     - "80:80"
    environment:
     - NGINX_PORT=80
    links:
     - front-test
  front:
    build: 
        context: ./front/
        dockerfile: Dockerfile
    ports:
     - "3000"
    links:
     - api
  api:
    build: ./api/
    ports:
     - "8080"
    links:
     - server
  server:
    build: ./server/
    ports:
     - "9999"
  front-test:
    build: 
        context: ./front/
        dockerfile: Dockerfile.test
    links:
     - front