version: '3'

services:
  server:
    build: ./server/
    ports:
     - "9999"
  api:
    build: ./api/
    ports:
     - "8080"
    links:
     - server
  front:
    build: ./front/
    ports:
     - "3000"
    links:
     - api
  nginx:
    build: ./nginx/
    ports:
     - "80:80"
    environment:
     - NGINX_PORT=80
    links:
     - front